# Version Generator Plugin - 版本自动生成插件
# 自动从 Git 或文件生成版本号

include(CMakeParseArguments)

# 注册插件
register_plugin(
    NAME "version_generator"
    DESCRIPTION "Automatically generate version numbers from Git or version file"
    VERSION "1.0.0"
    AUTHOR "IDCU Team"
    HOOKS "pre_build"
    DEPENDS ""
)

# 从 Git 生成版本号
function(_version_from_git RESULT_VAR)
    if(NOT EXISTS "${CMAKE_SOURCE_DIR}/.git")
        set(${RESULT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    find_package(Git QUIET)
    if(NOT GIT_FOUND)
        set(${RESULT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    # 尝试获取最新 tag
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=0
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_TAG
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )

    # 获取 commit 数量
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-list --count HEAD
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_COMMIT_COUNT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )

    # 获取短 commit hash
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_COMMIT_SHORT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )

    # 检查工作区是否有修改
    execute_process(
        COMMAND ${GIT_EXECUTABLE} status --porcelain
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_STATUS
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )

    if(GIT_STATUS)
        set(GIT_DIRTY "-dirty")
    else()
        set(GIT_DIRTY "")
    endif()

    # 组合版本号
    if(GIT_TAG)
        # 从 tag 解析主版本号
        string(REGEX REPLACE "^v?([0-9]+)\\.([0-9]+)\\.([0-9]+).*$" "\\1" MAJOR "${GIT_TAG}")
        string(REGEX REPLACE "^v?([0-9]+)\\.([0-9]+)\\.([0-9]+).*$" "\\2" MINOR "${GIT_TAG}")
        string(REGEX REPLACE "^v?([0-9]+)\\.([0-9]+)\\.([0-9]+).*$" "\\3" PATCH "${GIT_TAG}")

        if(NOT GIT_COMMIT_COUNT)
            set(GIT_COMMIT_COUNT "0")
        endif()

        set(VERSION "${MAJOR}.${MINOR}.${PATCH}.${GIT_COMMIT_COUNT}+${GIT_COMMIT_SHORT}${GIT_DIRTY}")
    elseif(GIT_COMMIT_COUNT AND GIT_COMMIT_SHORT)
        # 没有 tag，使用 commit count 和 hash
        set(VERSION "0.0.${GIT_COMMIT_COUNT}+${GIT_COMMIT_SHORT}${GIT_DIRTY}")
    else()
        set(VERSION "")
    endif()

    set(${RESULT_VAR} "${VERSION}" PARENT_SCOPE)
endfunction()

# 从版本文件读取版本号
function(_version_from_file RESULT_VAR)
    set(VERSION_FILES
        "${CMAKE_SOURCE_DIR}/VERSION"
        "${CMAKE_SOURCE_DIR}/version.txt"
        "${CMAKE_SOURCE_DIR}/.version"
    )

    foreach(VERSION_FILE ${VERSION_FILES})
        if(EXISTS "${VERSION_FILE}")
            file(STRINGS "${VERSION_FILE}" VERSION_CONTENT LIMIT_COUNT 1)
            if(VERSION_CONTENT)
                string(STRIP "${VERSION_CONTENT}" VERSION_CONTENT)
                set(${RESULT_VAR} "${VERSION_CONTENT}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endforeach()

    set(${RESULT_VAR} "" PARENT_SCOPE)
endfunction()

# 生成 version.h 文件
function(_generate_version_header)
    cmake_parse_arguments(
        GEN_VERSION
        ""
        "OUTPUT_DIR;MODULE_NAME;VERSION"
        ""
        ${ARGN}
    )

    if(NOT GEN_VERSION_OUTPUT_DIR)
        set(GEN_VERSION_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/include")
    endif()

    if(NOT GEN_VERSION_MODULE_NAME)
        message(FATAL_ERROR "MODULE_NAME is required for generate_version_header")
    endif()

    if(NOT GEN_VERSION_VERSION)
        set(GEN_VERSION_VERSION "1.0.0")
    endif()

    # 解析版本号
    string(REGEX REPLACE "^([0-9]+)\\.([0-9]+)\\.([0-9]+).*$" "\\1" VERSION_MAJOR "${GEN_VERSION_VERSION}")
    string(REGEX REPLACE "^([0-9]+)\\.([0-9]+)\\.([0-9]+).*$" "\\2" VERSION_MINOR "${GEN_VERSION_VERSION}")
    string(REGEX REPLACE "^([0-9]+)\\.([0-9]+)\\.([0-9]+).*$" "\\3" VERSION_PATCH "${GEN_VERSION_VERSION}")

    # 提取 build metadata
    string(FIND "${GEN_VERSION_VERSION}" "+" PLUS_POS)
    if(PLUS_POS GREATER -1)
        math(EXPR BUILD_START "${PLUS_POS} + 1")
        string(SUBSTRING "${GEN_VERSION_VERSION}" ${BUILD_START} -1 VERSION_BUILD)
    else()
        set(VERSION_BUILD "")
    endif()

    # 创建输出目录
    file(MAKE_DIRECTORY "${GEN_VERSION_OUTPUT_DIR}")

    string(TOUPPER "${GEN_VERSION_MODULE_NAME}" MODULE_NAME_UPPER)
    
    # 将连字符替换为下划线，生成安全的文件名
    string(REPLACE "-" "_" MODULE_NAME_SAFE "${GEN_VERSION_MODULE_NAME}")
    string(TOUPPER "${MODULE_NAME_SAFE}" MODULE_NAME_UPPER_SAFE)

    # 生成头文件内容
    set(HEADER_CONTENT "/*\n")
    string(APPEND HEADER_CONTENT " * Auto-generated version header\n")
    string(APPEND HEADER_CONTENT " * Generated by version_generator plugin\n")
    string(APPEND HEADER_CONTENT " */\n\n")
    string(APPEND HEADER_CONTENT "#ifndef ${MODULE_NAME_UPPER_SAFE}_VERSION_H\n")
    string(APPEND HEADER_CONTENT "#define ${MODULE_NAME_UPPER_SAFE}_VERSION_H\n\n")
    string(APPEND HEADER_CONTENT "#define ${MODULE_NAME_UPPER_SAFE}_VERSION \"${GEN_VERSION_VERSION}\"\n")
    string(APPEND HEADER_CONTENT "#define ${MODULE_NAME_UPPER_SAFE}_VERSION_MAJOR ${VERSION_MAJOR}\n")
    string(APPEND HEADER_CONTENT "#define ${MODULE_NAME_UPPER_SAFE}_VERSION_MINOR ${VERSION_MINOR}\n")
    string(APPEND HEADER_CONTENT "#define ${MODULE_NAME_UPPER_SAFE}_VERSION_PATCH ${VERSION_PATCH}\n")
    if(VERSION_BUILD)
        string(APPEND HEADER_CONTENT "#define ${MODULE_NAME_UPPER_SAFE}_VERSION_BUILD \"${VERSION_BUILD}\"\n")
    endif()
    string(APPEND HEADER_CONTENT "\n#endif /* ${MODULE_NAME_UPPER_SAFE}_VERSION_H */\n")

    set(HEADER_PATH "${GEN_VERSION_OUTPUT_DIR}/${MODULE_NAME_SAFE}_version.h")
    file(WRITE "${HEADER_PATH}" "${HEADER_CONTENT}")

    message(STATUS "Generated version header: ${HEADER_PATH}")

    # 将头文件目录添加到 include 路径（在 module_build_core 中处理）
    # target_include_directories(${GEN_VERSION_MODULE_NAME} PRIVATE "${GEN_VERSION_OUTPUT_DIR}")
endfunction()

# 钩子分发函数
function(version_generator_dispatch_hook)
    cmake_parse_arguments(
        DISPATCH
        ""
        "HOOK_NAME;MODULE_DIR;MODULE_NAME;MODULE_VERSION"
        ""
        ${ARGN}
    )

    if(DISPATCH_HOOK_NAME STREQUAL "pre_build")
        version_generator_pre_build(
            MODULE_DIR "${DISPATCH_MODULE_DIR}"
            MODULE_NAME "${DISPATCH_MODULE_NAME}"
            MODULE_VERSION "${DISPATCH_MODULE_VERSION}"
        )
    endif()
endfunction()

# pre_build 钩子实现
function(version_generator_pre_build)
    cmake_parse_arguments(
        PLUGIN_HOOK
        ""
        "MODULE_DIR;MODULE_NAME;MODULE_VERSION"
        ""
        ${ARGN}
    )

    message(STATUS "[version_generator] Running pre_build hook for ${PLUGIN_HOOK_MODULE_NAME}")

    # 尝试获取版本号
    set(GENERATED_VERSION "${PLUGIN_HOOK_MODULE_VERSION}")

    # 优先从 Git 获取
    _version_from_git(GIT_VERSION)
    if(GIT_VERSION)
        set(GENERATED_VERSION "${GIT_VERSION}")
        message(STATUS "[version_generator] Got version from Git: ${GENERATED_VERSION}")
    else()
        # 从版本文件获取
        _version_from_file(FILE_VERSION)
        if(FILE_VERSION)
            set(GENERATED_VERSION "${FILE_VERSION}")
            message(STATUS "[version_generator] Got version from file: ${GENERATED_VERSION}")
        else()
            message(STATUS "[version_generator] Using default version: ${GENERATED_VERSION}")
        endif()
    endif()

    # 生成版本头文件
    _generate_version_header(
        MODULE_NAME "${PLUGIN_HOOK_MODULE_NAME}"
        VERSION "${GENERATED_VERSION}"
    )

    # 更新 CMake 项目版本 - 注意：这里需要小心，因为目标可能还没创建
    if(TARGET "${PLUGIN_HOOK_MODULE_NAME}")
        set_property(TARGET "${PLUGIN_HOOK_MODULE_NAME}" PROPERTY VERSION "${GENERATED_VERSION}")
    endif()

    message(STATUS "[version_generator] pre_build hook completed")
endfunction()
