# 基础模块
json        json_module_get
yaml        yaml_module_get
platform    platform_module_get
config      config_module_get

# 业务模块
file        file_module_get
editor      editor_module_get
scanner     scanner_module_get
