add_subdirectory(core-module)
add_subdirectory(log-module)
add_subdirectory(config-module)
add_subdirectory(heartbeat)
add_subdirectory(metrics-module)
add_subdirectory(task-queue)
add_subdirectory(healthcheck-module)
add_subdirectory(alert-module)
add_subdirectory(collect-module)
add_subdirectory(cache-module)
add_subdirectory(storage-module)
add_subdirectory(security-module)
add_subdirectory(http-client-module)
add_subdirectory(http-management-module)
