# 平台检测模块
# 检测并配置平台、架构、编译器等信息

# 跨平台检测和配置
if(WIN32)
    set(PLATFORM_NAME "windows")
    set(PLATFORM_FAMILY "windows")
    set(LIB_PREFIX "")
    set(LIB_SHARED_SUFFIX ".dll")
    set(LIB_STATIC_SUFFIX ".lib")
    set(EXE_SUFFIX ".exe")
    set(PLATFORM_PATH_SEPARATOR ";")
elseif(APPLE)
    set(PLATFORM_NAME "macos")
    set(PLATFORM_FAMILY "unix")
    set(LIB_PREFIX "lib")
    set(LIB_SHARED_SUFFIX ".dylib")
    set(LIB_STATIC_SUFFIX ".a")
    set(EXE_SUFFIX "")
    set(PLATFORM_PATH_SEPARATOR ":")
elseif(UNIX)
    set(PLATFORM_NAME "linux")
    set(PLATFORM_FAMILY "unix")
    set(LIB_PREFIX "lib")
    set(LIB_SHARED_SUFFIX ".so")
    set(LIB_STATIC_SUFFIX ".a")
    set(EXE_SUFFIX "")
    set(PLATFORM_PATH_SEPARATOR ":")
else()
    set(PLATFORM_NAME "unknown")
    set(PLATFORM_FAMILY "unknown")
    set(LIB_PREFIX "lib")
    set(LIB_SHARED_SUFFIX ".so")
    set(LIB_STATIC_SUFFIX ".a")
    set(EXE_SUFFIX "")
    set(PLATFORM_PATH_SEPARATOR ":")
endif()

# 架构检测
if(CMAKE_SYSTEM_PROCESSOR MATCHES "amd64|AMD64|x86_64|x64")
    set(ARCH_NAME "x86_64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|ARM64|aarch64|AARCH64")
    set(ARCH_NAME "arm64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|ARM")
    set(ARCH_NAME "arm")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i386|i686|x86")
    set(ARCH_NAME "x86")
else()
    set(ARCH_NAME "${CMAKE_SYSTEM_PROCESSOR}")
endif()

# 编译器检测
if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
    set(COMPILER_NAME "msvc")
elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set(COMPILER_NAME "gcc")
elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
    set(COMPILER_NAME "clang")
elseif(CMAKE_C_COMPILER_ID STREQUAL "Intel")
    set(COMPILER_NAME "intel")
else()
    set(COMPILER_NAME "unknown")
endif()
