# libs/CMakeLists.txt

add_subdirectory(idcu-common)
add_subdirectory(idcu-module-build)
add_subdirectory(idcu-testframework)
add_subdirectory(idcu-module-system)
add_subdirectory(idcu-coroutine)
add_subdirectory(idcu-msgbus)
add_subdirectory(idcu-microkernel)
add_subdirectory(idcu-sdk)
add_subdirectory(idcu-log)
